#ifndef CONSTANTS_H
#define CONSTANTS_H

#define ERROR 0
#define INVALID "Z"
#define MAX_SIZE 15

#define ROMAN_CHAR_I 'I'
#define ROMAN_CHAR_V 'V'
#define ROMAN_CHAR_X 'X'
#define ROMAN_CHAR_L 'L'
#define ROMAN_CHAR_C 'C'
#define ROMAN_CHAR_D 'D'
#define ROMAN_CHAR_M 'M'

#define ARABIC_ONE 1
#define ARABIC_FIVE 5
#define ARABIC_TEN 10
#define ARABIC_FIFTY 50
#define ARABIC_ONE_HUNDRED 100
#define ARABIC_FIVE_HUNDRED 500
#define ARABIC_ONE_THOUSAND 1000

#define SMALLER_MAX_REPEAT 1
#define LARGER_MAX_REPEAT 3

#define PLACE_VALUE_LOOK_BACK 2

#define MINIMUM_REPEAT 1

#define ARABIC_NINE_HUNDRED 900
#define ARABIC_FOUR_HUNDRED 400
#define ARABIC_NINETY 90
#define ARABIC_FORTY 40
#define ARABIC_NINE 9
#define ARABIC_FOUR 4

#define ROMAN_STRING_M "M"
#define ROMAN_STRING_CM "CM"
#define ROMAN_STRING_D "D"
#define ROMAN_STRING_CD "CD"
#define ROMAN_STRING_C "C"
#define ROMAN_STRING_XC "XC"
#define ROMAN_STRING_L "L"
#define ROMAN_STRING_XL "XL"
#define ROMAN_STRING_X "X"
#define ROMAN_STRING_IX "IX"
#define ROMAN_STRING_V "V"
#define ROMAN_STRING_IV "IV"
#define ROMAN_STRING_I "I"

#define TOO_LARGE_ARABIC 4000
#define SMALLEST_ARABIC 1

#endif /* CONSTANTS_H */
